blank_issues_enabled: false
contact_links:
  - name: Twitter Developer Community
    url: https://twittercommunity.com/c/twitter-api/twitter-api-v2/
    about: For general API functionality questions, please ask in the developer forums.
